# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('icone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
                ('rg', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(9)])),
                ('foto', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('ddd', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=255)),
                ('banido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sinopse', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('data_lancamento', models.DateTimeField()),
                ('blockbuster', models.BooleanField(default=False)),
                ('capa', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacoes.Classificacao')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_fim', models.DateTimeField()),
                ('pago', models.BooleanField(default=False)),
                ('multa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacoes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='StatusLocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_locacao', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='locacao',
            name='status_locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacoes.StatusLocacao'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locacoes.Genero'),
        ),
        migrations.AddField(
            model_name='filme',
            name='locacoes',
            field=models.ManyToManyField(to='locacoes.Locacao'),
        ),
        migrations.AddField(
            model_name='filme',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
