# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificacao',
            options={'verbose_name': 'Classificação', 'verbose_name_plural': 'Classificações'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero'},
        ),
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name': 'Locação', 'verbose_name_plural': 'Locações'},
        ),
        migrations.AlterModelOptions(
            name='statuslocacao',
            options={'verbose_name': 'Status da Locação', 'verbose_name_plural': 'Status das Locações'},
        ),
    ]
