# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0002_auto_20170915_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='preco',
        ),
    ]
