# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0004_auto_20170921_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='data_lancamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
