# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0005_auto_20170921_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, default='', upload_to='filmes'),
        ),
    ]
